name: Waterfall
version: 0.0.1
description: Fluid control mobile application
authors: 
- Alexandre Cabral Bedeschi
homepage: https://github.com/o-mago/waterfall

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^1.0.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bluetooth_serial: ^0.2.2

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
