name: Waterfall
version: 0.0.1
description: Demonstrates how to use the `flutter_bluetooth_serial` plugin.
authors: 
- Alexandre Cabral Bedeschi
homepage: https://github.com/edufolly/flutter_bluetooth_serial/tree/master/example/

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^1.0.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bluetooth_serial: ^0.2.2

flutter:
  uses-material-design: true
